QOL

diff --git a/up b/up
--- a/up
+++ b/up
@@ -2,14 +2,34 @@
 
 CWD=$(pwd)
 
+ORS_API_KEY=no-need-for-local-run
+BITLY_API_KEY=bitlyApiKey
+BITLY_LOGIN=bitlyLogin
+
 if [[ $EUID -ne 0 ]]; then
     echo "This script should run as the root user (sudo)."
     echo "Use sudo or run as root user."
     exit 1
 fi
 
+if [ $# -ne 1 ]; then
+  echo "Usage: $0 <server_url>"
+  exit 1
+fi
+server_url="$1"
+if [[ ! "$server_url" =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
+  echo "Invalid server URL format: $server_url"
+  exit 1
+fi
+
 ./down
 cd $CWD
+
+sed "s/server.name.com/$server_url/g" premium-onpremise-ors > premium-onpremise-ors-new
+cp premium-onpremise-ors-new /etc/nginx/sites-available/premium-onpremise-ors
+ln -s /etc/nginx/sites-available/premium-onpremise-ors /etc/nginx/sites-enabled/premium-onpremise-ors
+rm premium-onpremise-ors-new
+systemctl restart nginx
 
 rm -f docker-compose.yml*
 wget https://raw.githubusercontent.com/GIScience/openrouteservice/master/docker-compose.yml
